export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';

export const START_DOWLOAD_TASKS = 'START_DOWLOAD_TASKS';
export const DOWLOAD_TASKS_SUCCESS = 'DOWLOAD_TASKS_SUCCESS';
export const DOWLOAD_TASKS_ERROR = 'DOWLOAD_TASKS_ERROR';

export const GET_TASK_DELETE = 'GET_TASK_DELETE';
export const TASK_DELETED_SUCCESS = 'TASK_DELETED_SUCCESS';
export const TASK_DELETED_ERROR = 'TASK_DELETED_ERROR';

export const GET_TASK_EDIT = 'GET_TASK_EDIT';
export const START_EDIT_TASK = 'START_EDIT_TASK';
export const TASK_EDIT_SUCCESS = 'TASK_EDIT_SUCCESS';
export const TASK_EDIT_ERROR = 'TASK_EDIT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';